version: '3'
services:

 api_server:
  build: .
  container_name: server
  ports:
  - 8888:8888
  env_file: ./deployment/loc.env
  volumes: 
  - .:/app
  links: 
  - intership_backend_postgres
  depends_on: 
  - intership_backend_postgres

 intership_backend_postgres:
  image: postgres:12-alpine
  container_name: db_postgres
  env_file: ./deployment/loc.env
  ports:
  - 5432:5432

 pgAdmin:
  image: dpage/pgadmin4:4.22
  container_name: pgAdmin
  depends_on: 
  - intership_backend_postgres
  ports:
  - 16555:80
  environment:
   PGADMIN_DEFAULT_EMAIL: developer@mail.ru
   PGADMIN_DEFAULT_PASSWORD: developer
  logging:
   driver: none
